name: Deploy to Hetzner
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy via Hetzner API
        env:
          HETZNER_API_KEY: ${{ secrets.HETZNER_API_KEY }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $HETZNER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"command": "reboot_server"}' \
            https://api.hetzner.cloud/v1/servers/<YOUR_SERVER_ID>/actions
