"use client";
import Card from "./Card"; import Chat from "./Chat"; import Dropzone from "./Dropzone"; import { REBECCA } from "@/lib/rebeccaConfig"; import { useEffect, useState } from "react";
async function proxy(action:string,payload:any){ const r=await fetch('/api/rebecca',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})}); return await r.json(); }
function List({items}:{items:any[]}){ return (<ul className="divide-y divide-zinc-800">{items.map((it:any,idx:number)=>(<li key={idx} className="py-2 text-sm"><div className="font-medium">{it.title||it.subject||it.name}</div>{it.time&&<div className="text-xs text-zinc-400">{String(it.time)}</div>}{it.snippet&&<div className="text-xs text-zinc-400">{it.snippet}</div>}</li>))}</ul>); }
export function ISHEPanel(){ const [emails,setEmails]=useState<any[]>([]); const [events,setEvents]=useState<any[]>([]); const [drive,setDrive]=useState<any[]>([]);
  useEffect(()=>{ (async()=>{ const e=await proxy('listEmails',{max:10}); setEmails(e?.items||[]); const c=await proxy('listCalendar',{max:10}); setEvents(c?.items||[]); const d=await proxy('listDrive',{scope:'ishe',max:15}); setDrive(d?.items||[]); })(); },[]);
  return (<div className="grid grid-cols-1 xl:grid-cols-2 gap-4"><Card title="Chat (ISHE)"><Chat/></Card><Card title="Quick Add Task (Heartbeat)"><QuickTask/></Card><Card title="Upcoming Appointments (Calendar)"><List items={events}/></Card><Card title="Recent Emails"><List items={emails}/></Card><Card title="ISHE Documents (Drive)"><List items={drive}/></Card><Card title="Drop Files to ISHE Drive"><Dropzone scope="ishe"/></Card></div>);
}
export function PersonalPanel(){ const [ok,setOk]=useState(false); const [pin,setPin]=useState(""); const [drive,setDrive]=useState<any[]>([]);
  useEffect(()=>{ if(ok){ (async()=>{ const d=await proxy('listDrive',{scope:'personal',max:20}); setDrive(d?.items||[]); })(); } },[ok]);
  if(!ok) return (<Card title="Enter PIN to access Personal Hub"><div className="flex gap-2"><input value={pin} onChange={e=>setPin(e.target.value)} placeholder="PIN" className="bg-zinc-900 border border-zinc-800 rounded-xl px-3 py-2"/><button onClick={()=>setOk(pin===REBECCA.personalPin)} className="px-3 py-2 rounded-xl bg-indigo-600">Unlock</button></div></Card>);
  return (<div className="grid grid-cols-1 xl:grid-cols-2 gap-4"><Card title="Chat (Personal)"><Chat/></Card><Card title="Personal Documents (Drive)"><List items={drive}/></Card><Card title="Drop Files to Personal Drive"><Dropzone scope="personal"/></Card></div>);
}
function QuickTask(){ const [text,setText]=useState(""); const add=async()=>{ if(!text.trim())return; await proxy('addTask',{ sheetId:REBECCA.sheetId, text}); setText(""); alert('Task added to Heartbeat ✅'); }; return (<div className="flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} placeholder="e.g., remind me to order valves" className="flex-1 bg-zinc-900 border border-zinc-800 rounded-xl px-3 py-2"/><button onClick={add} className="px-3 py-2 rounded-xl bg-indigo-600">Add</button></div>); }