name: Deploy Rebecca AI Studio
on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy app to Hetzner
        env:
          HETZNER_API: ${{ secrets.HETZNER_API }}
          HETZNER_SERVER_ID: ${{ secrets.HETZNER_SERVER_ID }}
        run: |
          echo "Rebuilding Hetzner server..."
          curl -X POST \
            -H "Authorization: Bearer ${HETZNER_API}" \
            -H "Content-Type: application/json" \
            -d '{"command":"rebuild","image":"ubuntu-22.04"}' \
            "https://api.hetzner.cloud/v1/servers/${HETZNER_SERVER_ID}/actions/rebuild"
